#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : conmon
Version  : 2.0.15
Release  : 4
URL      : https://github.com/containers/conmon/archive/v2.0.15.tar.gz
Source0  : https://github.com/containers/conmon/archive/v2.0.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: conmon-libexec = %{version}-%{release}
Requires: conmon-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : buildreq-meson
BuildRequires : glib-dev
BuildRequires : pkgconfig(glib-2.0)

%description
[![Total alerts](https://img.shields.io/lgtm/alerts/g/containers/conmon.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/containers/conmon/alerts/)

%package libexec
Summary: libexec components for the conmon package.
Group: Default
Requires: conmon-license = %{version}-%{release}

%description libexec
libexec components for the conmon package.


%package license
Summary: license components for the conmon package.
Group: Default

%description license
license components for the conmon package.


%prep
%setup -q -n conmon-2.0.15
cd %{_builddir}/conmon-2.0.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586363972
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/conmon
cp %{_builddir}/conmon-2.0.15/LICENSE %{buildroot}/usr/share/package-licenses/conmon/147d5d72b02467b04653ff37be85b8e201e9af66
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files libexec
%defattr(-,root,root,-)
/usr/libexec/podman/conmon

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/conmon/147d5d72b02467b04653ff37be85b8e201e9af66
